FROM docker.elastic.co/elasticsearch/elasticsearch:5.4.0

MAINTAINER Sajal Jain

ENV bootstrap_memory_lock=true

ENV ES_JAVA_OPTS="-Xms1g -Xmx2g"

ENV http.host=0.0.0.0

ENV transport.host=127.0.0.1

ENV xpack.security.enabled=false
